fix(dispatcher): Fix pickle error on formula factory when using spawn method
When multiprocessing `spawn` method is used, serializing the formula factory
method with pickle (on process spawn) fails and the following exception is raised :

AttributeError: Can't pickle local object 'DispatcherActor._create_factory.<locals>.factory'

This is due to the usage of a local function as formula factory, which pickle cannot serialize.